=== SteveBillss/IWPLP/testschema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="students">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="roll-no" type="xs:integer"/>
                            <xs:element name="dob" type="xs:date"/>
                            <xs:element name="courses">
                                <xs:complexType>
                                   <xs:sequence>
                                     <xs:element name="one" type="xs:string"/>
                                     <xs:element name="two" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>     
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SteveBillss/IWPLP/xmltesting.xml
<?xml version="1.0" encoding="UTF-8"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="testschema.xsd">
    <student>
        <name>M</name>
        <roll-no>60</roll-no>
        <dob>2002-03-27</dob>
        <courses>
            <one>DWDM</one>
            <two>CN</two>
        </courses>
    </student>
    <student>
        <name>N</name>
        <roll-no>62</roll-no>
        <dob>2002-03-20</dob>
        <courses>
            <one>DDM</one>
            <two>CNN</two>
        </courses>
    </student>
</students>
